In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4]) # slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2]) # start from 0 to 3 and jump 1
print(arr[::2]) # jump by one
print(arr[::-1]) # reverse
print(arr[3:])

3
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [8]:
#2D

import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr)
print(arr[0:2]) #row
print(arr[:,0]) #all rows | cols 0
print(arr[0,0]) #row ->1 col->1
print(arr[:1,2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 4]
1
[3]


In [1]:
import numpy as np
arr=np.array(([10,20],[30,40]))
print(arr[1,1])
print(arr[0,0])
print(arr[:,1])
print(arr[[0,1],[1,0]])
print(arr[[0,0],[1,1]])

40
10
[20 40]
[20 30]
[20 20]


In [ ]:
import numpy as np
arr=np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],[7562,86,647236],[9528,45,428760],[10788,17,183396]])
print(arr)
print(arr[0,0:2])
print(arr[[0,1],[2,1]])  #[0,2],[1,1]---> [0,1],[2,1]
print(arr[[4,5],[1,1]])
print(arr[[2,3,3,3],[0,0,1,2]])



[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7562     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[2453   75]
[183975     99]
[45 17]
[  4100   7562     86 647236]


In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
print(arr.ndim) # 3d
print("3D array --->",arr)
print("=>",arr[0])  #block
print("==>",arr[0,0]) #block -> row
print("===>",arr[0,0,0]) #block -> row -> col
#
print("=>>>>",arr[:,0])  #all block --> 0th row
print(arr[:,:,0])   #all  block -> all rowa -> 0th col


3
3D array ---> [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
=> [[1 2]
 [3 4]]
==> [1 2]
===> 1
=>>>> [[1 2]
 [5 6]]
[[1 3]
 [5 7]]


loops on numpy

In [ ]:
#for loop on numpy
#1D
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
for i in arr:
    print(i)

[10 20 30 40]
10
20
30
40


In [54]:
#2D
import numpy as np
arr=np.array([[10,20],[30,40]])
print(arr)
for i in arr:
    for j in i:
        print(j)

[[10 20]
 [30 40]]
10
20
30
40


In [55]:
#3D
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
for i in np.nditer(arr):  #numpy iterator
    print(i)

1
2
3
4
5
6
7
8


Sorting

In [61]:
#1D
import numpy as np
arr=np.array([10,20,30,45,65,2,41,13])
print(np.sort(arr))  #by default ascending
print(np.sort(arr)[::-1])

[ 2 10 13 20 30 41 45 65]
[65 45 41 30 20 13 10  2]


In [ ]:
#2D
import numpy as np
arr=np.array([[1,69,4],[33,13,5]])
# default sorting is row wise
print(np.sort(arr,axis=0)) #col wise
print(np.sort(arr,axis=1))  #row wise


[[ 1 13  4]
 [33 69  5]]
[[ 1  4 69]
 [ 5 13 33]]


In [72]:
#filter id

import numpy as np
arr=np.array([10,20,30,40])
print(arr[arr>30])

[40]


In [74]:
#where
import numpy as np
arr=np.array([10,20,30,40])
print(np.where(arr>20,"true","false"))
print(np.where(arr>20,2*arr,arr))

['false' 'false' 'true' 'true']
[10 20 60 80]
