In [26]:
#numpy | list
import numpy as np
import time

start= time.time()
sum1=0
for i in range(100000):
    sum1+= i*2
end = time.time()
#for list
print("for list : ",sum1,end-start)

#for numpy | array(array works on every element)
start1=time.time()
sum2=0
arr = np.arange(100000)*2
sum2=arr.sum()
end1=time.time()
print("for array : ",sum2,end1-start1)


for list :  9999900000 0.01265573501586914
for array :  9999900000 0.0009996891021728516


In [27]:
import time as t 
print(t.time())

1781859645.78987


In [28]:
#zeros

import numpy as np
#array 1D
arr=np.zeros(5)
print(arr)


arr2=np.zeros(5)+7  # it shows 7 by the use of zeros
print(arr2)

#array 2D
arr1=np.zeros((2,3)) #2rows and 3 columns
print(arr1)


[0. 0. 0. 0. 0.]
[7. 7. 7. 7. 7.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#ones

import numpy as np
#array 1D
arr=np.ones(5)
print(arr)

#array 2D
arr1=np.ones((2,3)) #2rows and 3 columns
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#full 

import numpy as np
#array1D
arr=np.full((5),7)   #full((5),7) -->  5 times 7
print(arr)

#array2D
arr1=np.full((2,3),5)
print(arr1)

[7 7 7 7 7]
[[5 5 5]
 [5 5 5]]


In [31]:
#random number

import numpy as np
print(np.random.randint(1,10))

6


In [32]:
# array opr on zeros | ones | full

import numpy as np

arr = np.zeros(5)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float

# 2d
print("2d zeros start")

arr1 = np.zeros((3, 2))

print(arr1)
print(arr1.shape)   # (3, 2)
print(arr1.ndim)    # 2
print(arr1.size)    # 6
print(arr1.dtype)   # float

[0. 0. 0. 0. 0.]
(5,)
1
5
float64
2d zeros start
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


In [33]:
# array opr on zeros | ones | full

import numpy as np

arr = np.ones(5)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float

# 2d
print("2d ones start")

arr1 = np.ones((3, 2))

print(arr1)
print(arr1.shape)   # (3, 2)
print(arr1.ndim)    # 2
print(arr1.size)    # 6
print(arr1.dtype)   # float

[1. 1. 1. 1. 1.]
(5,)
1
5
float64
2d ones start
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)
2
6
float64


In [34]:
# array opr on zeros | ones | full

import numpy as np

arr = np.full((5),8)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # int

# 2d
print("2d full start")

arr1 = np.full((3, 2),8)

print(arr1)
print(arr1.shape)  
print(arr1.ndim)   
print(arr1.size)   
print(arr1.dtype)   

[8 8 8 8 8]
(5,)
1
5
int64
2d full start
[[8 8]
 [8 8]
 [8 8]]
(3, 2)
2
6
int64


Array Reshaping

In [43]:
#1D array

import numpy as np
arr=np.arange(6)
print(arr)

#2D array
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
print(arr1)

#another approach
arr2=arr.reshape(2,3) #2rowa and 3 columns
print(arr2)

[0 1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 1 2]
 [3 4 5]]


In [52]:
#flatten (convert to 1D)

import numpy as np
#2D
arr=np.arange(6)
arr1=arr.reshape(2,3)
print(arr1)

#flatten
arr_new=arr1.flatten()
arr_new[0]=100
print(arr1)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [54]:
#ravel(convert to 1D)

import numpy as np 
#2D
arr=np.arange(6).reshape(2,3)
print(arr)

#ravel
arr_new1=arr.ravel()
arr_new1[0]=200
print(arr)

[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]


flatten --> it can create a copy of original 
Ravel --> It can return view(original data)

In [58]:
#transpose

import numpy as np
arr=np.arange(6).reshape(2,3)
print(arr)

print(np.transpose(arr))

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
